# Generated by Django 5.0.3 on 2024-03-08 14:03

import websites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=2083, null=True)),
                ('address', models.CharField(max_length=2083, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_click_date', models.DateTimeField(null=True)),
                ('click_times', models.IntegerField(default=0, null=True)),
                ('website_image_url', models.CharField(max_length=2083, null=True)),
                ('website_image', models.ImageField(blank=True, null=True, upload_to=websites.models.upload_location)),
                ('website_index_position_num', models.IntegerField(default=999, null=True)),
            ],
        ),
    ]
